defmodule Trasa.Rag.LLM.OpenAI do
  @moduledoc """
  Provides an implementation of the `Trasa.Rag.LLMProvider` behaviour for interacting with OpenAI's GPT models.
  """

  @behaviour Trasa.Rag.LLMProvider

  @doc """
  Completes a given prompt using the OpenAI GPT-3.5 Turbo model, contextualized with a provided context.

  ## Parameters
  - `context`: The context string to be prepended to the prompt for the AI.
  - `prompt`: The user's input prompt to which the AI should respond.

  ## Returns
  - The text generated by the AI in response to the prompt.
  """
  def complete(context, prompt) do
    {:ok, %{choices: [%{"message" => %{"content" => text}} | _]}} =
      OpenAI.chat_completion(
        model: "gpt-3.5-turbo",
        messages: [
          %{
            role: "system",
            content: context
          },
          %{role: "user", content: prompt}
        ]
      )

    text
  end
end
